<?php
/*
* implements HOOK_form_alter().
*/
function custom_user_profile_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_profile_form') {
    //array_unshift($form['#validate'], '_custom_user_profile_validate');
    $form['#validate'][] = '_custom_user_profile_validate';
  }
}

/*
* Implements _custom_user_profile_validate().
* Setting up profile image
*/
function _custom_user_profile_validate($form, &$form_state){
  $last_user_gallery = $form_state['values']['field_user_gallery'][LANGUAGE_NONE];
  //Get last picture gallery
  $last_user_gallery = (count(array_filter(array_keys($last_user_gallery), function($key) { return is_int($key); })))-1;
  $last_user_gallery = $form_state['values']['field_user_gallery'][LANGUAGE_NONE][$last_user_gallery];

  //Get last picture in the last gallery
  $last_image = end($last_user_gallery['field_image'][LANGUAGE_NONE]);

  //If file is Not uploaded by AJAX
  if($last_image['fid'] != 0){
    $last_image = file_load($last_image['fid']);
    //Check if profile is already set then replace, otherwise create new in else
    if(isset($form_state['values']['picture'])){
      $profile_image = $form_state['values']['picture'];
      _custom_user_profile_assign($profile_image, $last_image);
    }else{
      $form_state['values']['picture'] = $last_image;
    }
  }else{
    //If file is already uploaded by AJAX
    $second_last = $last_user_gallery['field_image'][LANGUAGE_NONE];
    $second_last = $second_last[count($second_last)-2];
    if(isset($second_last)){
      $second_last = file_load($second_last['fid']);
      //Check if profile is already set then replace, otherwise create new in else
      if(isset($form_state['values']['picture'])){
        $profile_image = $form_state['values']['picture'];
        _custom_user_profile_assign($profile_image, $second_last);
      }else{
        $form_state['values']['picture'] = $second_last;
      }
    }
  }
}

/*
 * Implements _custom_user_profile_assign().
*/
function _custom_user_profile_assign($profile_image, $array){
  $profile_image->fid = $array->fid;
  $profile_image->filename = $array->filename;
  $profile_image->uri = $array->uri;
  $profile_image->filemime = $array->filemime;
  $profile_image->filesize = $array->filesize;
}
